### ISSUE TITLE
EUIDLOOKUP error

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [getferdi/server-docker#1]
Hi guys,

Unfortunately I can't get the Docker container to run, I started it without specifying a user. Also tried to create and specify another user but that gives me other errors...

```
**** Installing AdonisJS and deps ****

npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
/usr/bin/adonis -> /usr/lib/node_modules/@adonisjs/cli/index.js

> nodemon@1.19.3 postinstall /usr/lib/node_modules/@adonisjs/cli/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@adonisjs/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EUIDLOOKUP
npm ERR! lifecycle could not get uid/gid
npm ERR! lifecycle [ 'nobody', 0 ]
npm ERR! lifecycle
npm ERR!
npm ERR! Failed to look up the user/group for running scripts.
npm ERR!
npm ERR! Try again with a different --user or --group settings, or
npm ERR! run with --unsafe-perm to execute scripts as root.

npm ERR! A complete log of this run can be found in:
```

Hope you can help me :)

**Comment by h3x4d3c1m4l** [comment]
Relevant piece of docker compose config:

```
  ferdi-server:
    image: getferdi/ferdi-server
    container_name: service-ferdi-server
    environment:
      IS_CREATION_ENABLED: "true"
      CONNECT_WITH_FRANZ: "true"
    volumes:
      - ../volumes/ferdi/config:/config
      - ../volumes/ferdi/database:/usr/src/app/database
      - ../volumes/ferdi/recipes:/usr/src/app/recipes
    expose:
      - "80"
    restart: always
```
